### PR TITLE
Issue 373, v2: Upgrade rdf-toolkit and Java

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This Pull Request will resolve all requirements of [Issue 373](https://github.com/ucoProject/UCO/issues/373).

This PR adjusts the strategy of v1, [PR 386](https://github.com/ucoProject/UCO/pull/386), due to issues having been found when running a normalized file through `rdf-toolkit` multiple times.  Issue documentation is on [CASE-Examples PR 75](https://github.com/casework/CASE-Examples/pull/75).  `pre-commit` usage is removed from v2 of resolving Issue 373.

Review steps taken:

- [x] Pull request is against correct branch
- [x] CI passes in (CASE/UCO) feature branch
- [ ] CI passes in (CASE/UCO) current unstable branch ([merge-commit](#TODO-commit))
- [ ] Impact on SHACL validation [reviewed](#TODO-commit) for CASE-Examples
- [ ] Impact on SHACL validation [remediated](#TODO-commit) for CASE-Examples 
- [ ] Impact on SHACL validation [reviewed](#TODO-commit) for casework.github.io
- [ ] Impact on SHACL validation [remediated](#TODO-commit) for casework.github.io

### CODE REVIEW

**Review by plbt5 — APPROVED** [review]
The update changes all ordered lists into sets of IRIs. The application can only select one set element.

**Review by plbt5 — APPROVED** [review]
If I'm correct, the wget on `...rdf-toolkit-build/lastSuccessfulBuild/...` might pull a new version in the future. This demands the new rdf-toolkit version to be backwards compatible with the current one to prevent the tool to potentially crash. 

At the same time, constraining the toolkit with a SHA512 to one single version only, prevent new versions to be applied, *and* might make the tool to stall for different builds.

I assume this to be the intended behaviour.

**Review by plbt5 — APPROVED** [review]

**Comment by ajnelson-nist** [comment]
> The update changes all ordered lists into sets of IRIs. The application can only select one set element.

I'm not quite sure I follow this remark - the syntactic style of the ordered lists is changed, but they have not been converted into sets.  `( ... )` is Turtle shorthand for an RDF List.  Or is there something I'm missing?

**Comment by ajnelson-nist** [comment]
Closing as superseded by [PR 398](https://github.com/ucoProject/UCO/pull/395).

**Pull request closed without merging**
