### PR TITLE
Issue 431: Remove core:id

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This Pull Request resolves all requirements of Issue #431 .

# Coordination

- [x] Pull request is against correct branch
- [x] Pull Request is in, or reverted to, Draft status before Solutions Approval vote has passed.
- [x] CI passes in (CASE/UCO) feature branch
- [x] CI passes in (CASE/UCO) current unstable branch ([56d0976](https://github.com/ucoProject/UCO-Archive/commit/56d09761cd3fb51a8881ea6f481700ee1276149b))
- [x] CI passes in CASE current `unstable` branch tracking UCO's `unstable` as submodule ([2058e66](https://github.com/casework/CASE-Archive/commit/2058e66e9e8042509c151a1d9b722d8badd4aa34)) *(This is not the adopting commit, but 193004b is in the history of the adopted UCO `unstable` state)*
- [x] Impact on SHACL validation [reviewed](https://github.com/casework/CASE-Examples/commit/52cff077401b2f232e2d1a96d2ecc3626bda5680) for CASE-Examples
- [x] Impact on SHACL validation remediated for CASE-Examples *(N/A)*
- [x] Impact on SHACL validation [reviewed](https://github.com/casework/casework.github.io/commit/cc043437152044565da7fe5919124b9f0677823c) for casework.github.io
- [x] Impact on SHACL validation remediated for casework.github.io (*N/A)*
- [x] Solutions Approval vote logged on corresponding Issue (once logged, can be taken out of Draft PR status)

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Converting to Draft until Solutions Approval vote is logged.

**Comment by ajnelson-nist** [comment]
Follow-on patch coming to address merge conflict.

**Comment by ajnelson-nist** [comment]
@plbt5 , @eoghanscasey , @b0bkaT - once CI finishes, this PR is ready for review and merge.  The first to review may merge.

**Review by plbt5 — APPROVED** [review]
Visually reviewed; seems correct

**Pull request merged**
