### PR TITLE
Issue 433: Remove core:type

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This Pull Request resolves all requirements of Issue #433 .

# Coordination

- [x] Pull request is against correct branch
- [x] Pull Request is in, or reverted to, Draft status before Solutions Approval vote has passed.
- [x] CI passes in (CASE/UCO) feature branch
- [x] CI passes in (CASE/UCO) current unstable branch ([193004b](https://github.com/ucoProject/UCO-Archive/commit/193004b9896903f92b3b33450d53d070169c6e02))
- [x] CI passes in CASE current `unstable` branch tracking UCO's `unstable` as submodule ([2058e66](https://github.com/casework/CASE-Archive/commit/2058e66e9e8042509c151a1d9b722d8badd4aa34)) *(This is not the adopting commit, but `193004b` is in the history of the adopted UCO `unstable` state)*
- [x] Impact on SHACL validation [reviewed](https://github.com/casework/CASE-Examples/commit/438040cc276b5104f5cd968f0b7d19e3093b877c) for CASE-Examples
- [x] Impact on SHACL validation remediated for CASE-Examples *(N/A)*
- [x] Impact on SHACL validation [reviewed](https://github.com/casework/casework.github.io/commit/9bd65890543f9fd3429e053b83e6812f9a9b8600) for casework.github.io
- [x] Impact on SHACL validation remediated for casework.github.io *(N/A)*
- [x] Solutions Approval vote logged on corresponding Issue (once logged, can be taken out of Draft PR status)

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Converting to Draft until Solutions Approval vote is logged.

**Comment by ajnelson-nist** [comment]
@eoghanscasey , @b0bkaT , or @plbt5 - this is ready for review and merge.  The first to review may merge.

**Review by plbt5 — APPROVED** [review]
Visually reviewed; seems correct.

**Comment by plbt5** [comment]
I don't feel knowledgable enough to resolve conflicts and leave that up to @ajnelson-nist

**Review by b0bkaT — APPROVED** [review]

**Pull request merged**
