### PR TITLE
Rename ToolConfigurationFacet from ToolConfigurationTypeFacet in Update tool.ttl (v2)

### PR DESCRIPTION
**Pull request by ajnelson-nist**
*(Chair note: This Pull Request supersedes [PR 452](https://github.com/ucoProject/UCO/pull/452), which had branching issues that could not be resolved through the Github interface.)*

This pull request relates to [Issue #451](https://github.com/ucoProject/UCO/issues/451), and the updating of the turtle file tool.ttl

Renaming of old Facet ToolConfigurationTypeFacet to ToolConfigurationFacet, which required changes to four (4) lines to within  the turtle file **_tool.ttl_**.

The changes made are:
1. Remove the text "Type" from the facet "ToolConfigurationTypeFacet", so that it becomes "**ToolConfigurationFacet**" (changes on lines 359, 365, 379), and 
2. Update the comment by replacing "A tool configuration type facet...." with "A **tool configuration facet**...." (line 366).

The change is expected to be low risk

# Coordination

- [x] Pull Request is against correct branch
- [x] Pull Request is in, or reverted to, Draft status before Solutions Approval vote has passed.
- [ ] CI passes in UCO feature branch
- [ ] CI passes in UCO current `unstable` branch ([merge-commit](#TODO-commit))
- [ ] CI passes in CASE current `unstable` branch tracking UCO's `unstable` as submodule ([merge-commit](#TODO-commit))
- [ ] Impact on SHACL validation [reviewed](#TODO-commit) for CASE-Examples
- [ ] Impact on SHACL validation [remediated](#TODO-commit) for CASE-Examples 
- [ ] Impact on SHACL validation [reviewed](#TODO-commit) for casework.github.io
- [ ] Impact on SHACL validation [remediated](#TODO-commit) for casework.github.io 
- [x] Milestone linked
- [ ] Solutions Approval vote logged on corresponding Issue (once logged, can be taken out of Draft PR status)

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Converting to Draft until Solutions Approval vote is logged.

**Comment by gwebb-case** [comment]
Hi @ajnelson-nist, is this all in-hand, or do you want me to redo the changes and create a new pull request targeting the develop branch?
I have deleted my previous master commit as the pull request was closed, and re-forked the full UCO repository, and can now target the changes within the develop branch - but will put it on hold until you say to proceed.
To make sure I don't don't mess up this time or in the future, when committing changes should I select
1. Commit directly to the develop branch; or
2. Create a new branch for this commit and start a pull request. 

guessing option (2) but may be wrong.

**Comment by ajnelson-nist** [comment]
@gwebb-case - no further effort is needed from you on this.  This had to be done with a new Pull Request because PRs are tied to the submitting branch name.  But, it's done enough now, and ready for committee review.

**Review by sbarnum — APPROVED** [review]
These changes look appropriate and are limited to the proposed changes agreed to in the Requirements review approval.

**Comment by ajnelson-nist** [comment]
Oh.  Whoops.  This PR is obviated by the concept being absorbed into the `configuration` namespace as part of resolving [Issue 432](https://github.com/ucoProject/UCO/issues/432).  When I resolved the merge conflict, the whole chunk @gwebb-case modified disappeared.  It migrated [here](https://github.com/ucoProject/UCO/commit/051970abe42c156b1313609ea5be1b0ae894b98e#diff-099fd15cc2440ff349fd94449a17dad1eee2311cb6eb1a78fd28c4a652abdb35R19).

I'm going to close the PR to avoid confusion in the Git history.  Thanks for your help in any case, @gwebb-case !

**Pull request closed without merging**
