### PR TITLE
Update observable.ttl

### PR DESCRIPTION
**Pull request by nsxtas**
added property shape to observable:MutexFacet and definition to observable:mutexName

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@nsxtas , thank you!  CI's churning along.  We'll run it through the administrivia review checklist soon (which for this will mainly help ensure it is documented in the release notes).

**Comment by ajnelson-nist** [comment]
Ah, sorry for the surprise, the checklist's first step is making sure the PR is filed against `develop`, per the [branching model this repository uses](https://cyberdomainontology.org/ontology/development/#branching) ("Git-flow" branching).

The Github interface causes a constraint that has tripped up enough people I'm going to suggest to the OC that we change the "Primary" branch to `develop` instead of `master`.

Are you able to force-push your changes as a patch so they start from the current state of `develop` instead of `master`?

**Comment by nsxtas** [comment]
@ajnelson-nist , added the changes to `develop` branch. should be good to go

**Comment by ajnelson-nist** [comment]
Thanks, @nsxtas !

I'm closing this PR as superseded by [PR 472](https://github.com/ucoProject/UCO/pull/472).

**Pull request closed without merging**
