### PR TITLE
SHACL implementation (CP-23)

### PR DESCRIPTION
**Pull request by b0bkaT**

### CODE REVIEW

**Comment by sbarnum** [comment]
I can see the CI failing but I am not understanding the cause. What do you mean by it expecting last line of tile to be blank? Which file?

**Comment by sbarnum** [comment]
FYI, I also caught an oversight in the changes for CP-69.
All of the typos had been fixed except for the NetworkConnection ones.
So, that is the other commit here.

**Comment by ajnelson-nist** [comment]
rdf-toolkit expects all normalized turtle files to end with a blank line.  Unfortunately, text editors (yours included) tend to remove trailing blank lines.  Git style guidance does the same.

The files you just touched had their trailing blank lines removed (uco.ttl and observable.ttl).

Sorry that my comment wasn't clear.  I commented on the patch and Github shifted that comment to the PR.

Thanks for the `NetworkConnetion` catch.

**Comment by sbarnum** [comment]
Ok. So, it sounds like the CI issue is not something I can fix but you can?
Other than that issue it should be ready to approve and merge into develop

**Comment by ajnelson-nist** [comment]
There are a few other minor matters reported by rdf-toolkit, sort order and dangling -da references.  I'm fixing now.

**Comment by ajnelson-nist** [comment]
The CI tests have returned to failing at the expected location based on the [pyshacl bug](https://github.com/RDFLib/pySHACL/issues/90).

It occurs to me this might be correctable with a pytest skipif based on the pyshacl version, so we could have this merge with a passing CI.  @sbarnum , would you prefer a passing CI, or merging and just "soft"-expecting CI to fail?

**Comment by ajnelson-nist** [comment]
...Eh, scratch that, it makes the Makefile a bit more complex.

I suggest merging now.  I've assigned the PR to you so you can merge if you concur.

**Comment by sbarnum** [comment]
I concur with merging as is.

**Pull request merged**
