### PR TITLE
Release 0.6.0 normalizing

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
I have at least one more commit to add to this PR.

**Comment by ajnelson-nist** [comment]
@sbarnum - please note that I had to apply one non-mechanical fix in [this patch](https://github.com/ucoProject/UCO/pull/241/commits/2f7a337c82877ee83abbdd5870d8fc68a8214a37).

**Comment by ajnelson-nist** [comment]
This is ready for review and merge.

**Comment by ajnelson-nist** [comment]
@sbarnum : I found the merge issue you identified, and believe it is the only *new* one.  I found three old ones fitting the same pattern with this script:

https://github.com/ajnelson-nist/CASE-Examples-QC/blob/ONT-419/src/confirm_singular_definitions.py

Otherwise, this is ready for your review and merge.

**Review by sbarnum — APPROVED** [review]

**Pull request merged**
