### PR TITLE
Solution implementation to Cp 378

### PR DESCRIPTION
**Pull request by plbt5**
This Pull Request resolves all ontology requirements of Issue #378 . For the documentation requirement, refer to [ucoproject.github.io's PR 41](https://github.com/ucoProject/ucoproject.github.io/pull/41)

Review steps taken:

- [x] Pull request is against correct branch
- [x] CI passes in (CASE/UCO) feature branch
- [x] CI passes in (CASE/UCO) current unstable branch ([merge-commit](https://github.com/ucoProject/UCO-Archive/commit/8b50aa0156305896b3d073843ae6a564e88cb521))
- [x] Impact on SHACL validation [reviewed](https://github.com/casework/CASE-Examples/commit/6c57a3bc95b7b74d99f1d2e7d68807ea01aa5713) for CASE-Examples
- [x] Impact on SHACL validation remediated for CASE-Examples *(N/A)*
- [x] Impact on SHACL validation [reviewed](https://github.com/casework/casework.github.io/commit/30bfda1be3adef334871022e0548798dd3e80413) for casework.github.io
- [x] Impact on SHACL validation remediated for casework.github.io *(N/A)*

### CODE REVIEW

**Comment by plbt5** [comment]
@ajnelson-nist I was able to throw a normalisation error by only ading one single triple statement *duh*. I'm not sure how to proceed.

**Comment by ajnelson-nist** [comment]
This was filed against `master`, not `develop`.  Can you update the PR's target to `develop`?  (It'd be nice if we could configure this repository to set that as the default...)

Also, about normalization - that statement needs to be inlined into the `core:Object` triples block.

**Comment by plbt5** [comment]
Wow, changing the base branch from `master` to `develop` for this PR was really simple. Learned a thing again 👍

**Comment by plbt5** [comment]
Wow, the change to normalise the code took hours. Not because the change itself was possible, but because I combined git local and global changes, and had a hard time to return from the mess I created with that. Remind me to never, ever, combine local and global git changes anymore.

**Pull request merged**
